# Generated by Django 6.0.3 on 2026-05-09 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('stock_minimo', models.PositiveIntegerField(default=10)),
                ('fecha_produccion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_registro_sistema', models.DateTimeField(auto_now_add=True)),
                ('estado_calidad', models.CharField(choices=[('ACEPTABLE', 'Aceptable'), ('MEDIO', 'Medio'), ('DAÑADO', 'Dañado')], default='ACEPTABLE', max_length=15)),
                ('esta_activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateField()),
                ('fecha_registro_real', models.DateTimeField(auto_now_add=True)),
                ('cantidad_recolectada', models.PositiveIntegerField()),
                ('mortalidad_del_dia', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_produccion', to='produccion.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
